input {
  beats {
    port => 5044

    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/config/certs/logstash/logstash.crt"
    ssl_key => "/usr/share/logstash/config/certs/logstash/logstash.pkcs8.key"
  }
}

filter {
  # Your filters
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]

    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => [
      "/usr/share/logstash/config/certs/ca/ca.crt"
    ]

    index => "hirkanet-logs-%{+YYYY.MM.dd}"
    manage_template => false
  }

  elasticsearch {
    hosts => ["https://elasticsearch:9200"]

    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => [
      "/usr/share/logstash/config/certs/ca/ca.crt"
    ]

    index => "hirkanet-dead-letter"
    manage_template => false
  }
}