input { beats { port => 5044 } }
filter {
  if [container][name] == "fortigate-app" {
    json { source => "message" target => "[@metadata][parsed]" tag_on_failure => ["hirkanet_json_parse_failure"] }
    if "hirkanet_json_parse_failure" not in [tags] {
      ruby { code => 'event.get("[@metadata][parsed]").each { |k,v| event.set(k,v) }' }
      if [@timestamp] { date { match => ["@timestamp", "ISO8601"] target => "@timestamp" } }
    }
  } else {
    mutate { add_field => { "[service][name]" => "postgres" "[event][dataset]" => "postgres.container" } }
  }
}
output {
  if "hirkanet_json_parse_failure" in [tags] {
    elasticsearch { hosts => ["https://elasticsearch:9200"] user => "elastic" password => "${ELASTIC_PASSWORD}" ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"] index => "hirkanet-dead-letter-%{+YYYY.MM.dd}" }
  } else {
    elasticsearch { hosts => ["https://elasticsearch:9200"] user => "elastic" password => "${ELASTIC_PASSWORD}" ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"] ilm_enabled => true ilm_rollover_alias => "hirkanet-logs" ilm_policy => "hirkanet-logs-policy" }
  }
}
