version = 5.7.0
archive_dir = /etc/letsencrypt/archive/hirkanet.com
cert = /etc/letsencrypt/live/hirkanet.com/cert.pem
privkey = /etc/letsencrypt/live/hirkanet.com/privkey.pem
chain = /etc/letsencrypt/live/hirkanet.com/chain.pem
fullchain = /etc/letsencrypt/live/hirkanet.com/fullchain.pem
[renewalparams]
account = c51dff3abac7506808521a9955175db5
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
