services:
  nginx:
    image: nginx:latest
    container_name: hirkanet-nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro

    networks:
      - hirkanet-network

networks:
  hirkanet-network:
    external: true
    name: hirkanetcom_default
